### ISSUE TITLE
Android Privacy issuies 

### ISSUE THREAD

**Issue by rumatoest** [LedgerHQ/ledger-wallet-android#9]
Hi.
You application has some privacy issues.

1. It does not locks when not used, but it must lock itself after about 5 minutes without any action from user or in background
2. It must not show app content while navigation between open apps. Many secure apps do it - you are not able to see app content only blank square until you'll bring app to foreground (and then probably you will be asked to unlock app)

**Comment by gre** [comment]
thanks for the issue.

These should be fixed on our develop branch.

**Comment by gre** [comment]
also, the correct repository is https://github.com/LedgerHQ/ledger-live-mobile
